/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.agrovacas.DAOVacasImpl;
import com.mycompany.agrovacas.Dashboard;
import com.mycompany.interfaces.DAOVacas;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lalom
 */
public class Ganados extends javax.swing.JPanel {

    /**
     * Creates new form MainC
     */
    public Ganados() {
        initComponents();
        initStyles();
        LoadGanado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   private void initStyles(){
       txt1.putClientProperty( "FlatLaf.styleClass", "h2" );
       txt1.setForeground(Color.black);
       searchtxt.putClientProperty("JTextField.placeholderText", "Ingrese Arete a buscar");
      
   }
   
   private void LoadGanado(){
       try{
           DAOVacas dao = new DAOVacasImpl();
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            dao.Listar("").forEach((u) -> {
            model.addRow(new Object[]{
                u.getId(),
                u.getArete(),
                u.getAlias(),
                u.getArete_bebe(),
                u.getRancho(),
                u.getFecha_nacimiento(),
                u.getRaza(),
                u.getEmpadre(),
                u.getFinalidad()
            });
        });  
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
       // Alinea la columna 0 (ID) al centro
       jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
       }catch(Exception e){
           System.out.println(e.getMessage());
       }
   }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Delete2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(858, 471));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        txt1.setText("Ganado");

        searchtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        search.setBackground(new java.awt.Color(0, 163, 0));
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.png"))); // NOI18N
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Arete", "Alias", "Arete bebe", "Rancho", "Fecha Nacimiento", "Raza", "Empadre", "Finalidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Delete.setBackground(new java.awt.Color(0, 163, 0));
        Delete.setText("Eliminar");
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Editar.setBackground(new java.awt.Color(0, 163, 0));
        Editar.setText("Editar");
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Delete2.setBackground(new java.awt.Color(0, 163, 0));
        Delete2.setText("Agregar");
        Delete2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Delete2)
                        .addGap(18, 18, 18)
                        .addComponent(Editar)
                        .addGap(18, 18, 18)
                        .addComponent(Delete))
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(searchtxt)
                            .addGap(18, 18, 18)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try{
            String VacaBuscar=searchtxt.getText();
            
            DAOVacas dao = new DAOVacasImpl();
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
           model.setRowCount(0);
           dao.Listar(VacaBuscar).forEach((u) -> {
            model.addRow(new Object[]{
                u.getId(),
                u.getArete(),
                u.getAlias(),
                u.getArete_bebe(),
                u.getRancho(),
                u.getFecha_nacimiento(),
                u.getRaza(),
                u.getEmpadre(),
                u.getFinalidad()
            });
        });  
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_searchActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
  
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DAOVacas dao = new DAOVacasImpl();
        
        if (jTable1.getSelectedRows().length < 1){
        javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar una vaca a Eliminar\n","AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        else{
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar la(s) vaca(s) seleccionada(s)?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;
        for (int i : jTable1.getSelectedRows()){                     
            try{
                dao.eliminar((int)(jTable1.getValueAt(i, 0)));
                model.removeRow(i);
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            
        }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
    if (jTable1.getSelectedRow() > -1){
        try{
        int id = (int)(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        DAOVacas dao = new DAOVacasImpl();
        Dashboard.ShowJPanel(new UpGanado(dao.getVacaByID(id)));
        } catch(Exception e){
        System.out.println(e.getMessage());
    }
    }
    else {
        javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar una vaca a editar\n","AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_EditarActionPerformed

    private void Delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete2ActionPerformed
        // TODO add your handling code here:
        Dashboard.ShowJPanel(new UpGanado());
    }//GEN-LAST:event_Delete2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Delete2;
    private javax.swing.JButton Editar;
    private javax.swing.JPanel bg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JLabel txt1;
    // End of variables declaration//GEN-END:variables
}
