/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.agrovacas.DAOVacasImpl;
import com.mycompany.interfaces.DAOVacas;
import com.mycompany.models.Vacas;
import java.awt.Color;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author lalom
 */
public class UpGanado extends javax.swing.JPanel {

    /**
     * Creates new form MainC
     */
    boolean isEdition = false;
    Vacas vacaEdition;
    public UpGanado() {
        initComponents();
        initStyles();
    }
    
    public UpGanado(Vacas vaca) {
        initComponents();
        isEdition = true;
        vacaEdition= vaca;
        initStyles();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   private void initStyles(){
       TitleG.putClientProperty( "FlatLaf.styleClass", "h1" );
       TitleG.setForeground(Color.black);
       aretes.putClientProperty( "FlatLaf.styleClass", "h2" );
       aretes.setForeground(Color.black);
       Alias.putClientProperty( "FlatLaf.styleClass", "h2" );
       Alias.setForeground(Color.black);
       AreteBebe.putClientProperty( "FlatLaf.styleClass", "h2" );
       AreteBebe.setForeground(Color.black);
       Nacimiento.putClientProperty( "FlatLaf.styleClass", "h2" );
       Nacimiento.setForeground(Color.black);
       Rancho.putClientProperty( "FlatLaf.styleClass", "h2" );
       Rancho.setForeground(Color.black);
       Raza.putClientProperty( "FlatLaf.styleClass", "h2" );
       Raza.setForeground(Color.black);
       Empadre.putClientProperty( "FlatLaf.styleClass", "h2" );
       Empadre.setForeground(Color.black);
       Finalidad.putClientProperty( "FlatLaf.styleClass", "h2" );
       Finalidad.setForeground(Color.black);
       
       //Estilizacion de los textfields
       AliasTxt.putClientProperty("JTextField.placeholderText", "Ingrese el Alias");
       AreteBebeTxt.putClientProperty("JTextField.placeholderText", "Ingrese el Arete de la madre solo si es necesario");
       aretesTxt.putClientProperty("JTextField.placeholderText", "Ingrese el Arete");
       RanchoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el Rancho perteneciente");
       RazaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la Raza");
       EmpadreTxt.putClientProperty("JTextField.placeholderText", "Ingrese el Empadre");
       FinalidadTxt.putClientProperty("JTextField.placeholderText", "Ingrese la Finalidad");
       
       if (isEdition){
           TitleG.setText("Editar Ganado");
           Agregar.setText("Guardar");
           if (vacaEdition != null){
               aretesTxt.setText(vacaEdition.getArete());
               AliasTxt.setText(vacaEdition.getAlias());
               AreteBebeTxt.setText(vacaEdition.getArete_bebe());
               RanchoTxt.setText(vacaEdition.getRancho());
               NacimientoDate.setDate(vacaEdition.getFecha_nacimiento());
               RazaTxt.setText(vacaEdition.getRaza());
               EmpadreTxt.setText(vacaEdition.getEmpadre());
               FinalidadTxt.setText(vacaEdition.getFinalidad());
           }
       }
   }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        TitleG = new javax.swing.JLabel();
        aretes = new javax.swing.JLabel();
        aretesTxt = new javax.swing.JTextField();
        Alias = new javax.swing.JLabel();
        AliasTxt = new javax.swing.JTextField();
        AreteBebeTxt = new javax.swing.JTextField();
        AreteBebe = new javax.swing.JLabel();
        RanchoTxt = new javax.swing.JTextField();
        Rancho = new javax.swing.JLabel();
        Nacimiento = new javax.swing.JLabel();
        NacimientoDate = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        EmpadreTxt = new javax.swing.JTextField();
        FinalidadTxt = new javax.swing.JTextField();
        Finalidad = new javax.swing.JLabel();
        Raza = new javax.swing.JLabel();
        RazaTxt = new javax.swing.JTextField();
        Empadre = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(858, 471));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        TitleG.setText("Subir un nuevo ganado");

        aretes.setText("Arete");

        aretesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aretesTxtActionPerformed(evt);
            }
        });

        Alias.setText("Alias");

        AliasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AliasTxtActionPerformed(evt);
            }
        });

        AreteBebe.setText("Arete bebe");

        RanchoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RanchoTxtActionPerformed(evt);
            }
        });

        Rancho.setText("Rancho");

        Nacimiento.setText("Fecha de nacimiento");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Finalidad.setText("Finalidad");

        Raza.setText("Raza");

        Empadre.setText("Empadre");

        Agregar.setBackground(new java.awt.Color(0, 163, 0));
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(TitleG, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addComponent(aretesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(aretes, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(245, 245, 245))
                    .addComponent(AliasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Alias, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(245, 245, 245))
                    .addComponent(AreteBebeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(RanchoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(NacimientoDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(AreteBebe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Rancho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(83, 83, 83))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)))
                .addGap(105, 105, 105)
                .addComponent(jSeparator2)
                .addGap(65, 65, 65)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RazaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(EmpadreTxt)
                    .addComponent(FinalidadTxt)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Finalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Empadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Raza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94))
                    .addComponent(Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TitleG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Raza, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RazaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Empadre, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmpadreTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Finalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FinalidadTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addGap(89, 89, 89))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(aretes, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aretesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Alias, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AliasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(AreteBebe, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AreteBebeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Rancho, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RanchoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NacimientoDate, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        String arete =aretesTxt.getText();
        String alias =AliasTxt.getText();
        String arete_bebe =AreteBebeTxt.getText();
        String rancho =RanchoTxt.getText();
       
        String raza =RazaTxt.getText();
        String empadre =EmpadreTxt.getText();
        String finalidad =FinalidadTxt.getText();
        
        java.util.Date fechaUtil = NacimientoDate.getDate();
        java.sql.Date fechaSql = null;
        if (fechaUtil != null) {
    fechaSql = new java.sql.Date(fechaUtil.getTime());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fecha de nacimiento válida.\n","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return; // Sale del método si no se seleccionó una fecha
        }
        if (arete.isEmpty() || alias.isEmpty() || rancho.isEmpty() || raza.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Rellena los campos obligatorios\n","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
          java.time.LocalDate fechaNacimiento = fechaUtil.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
          java.time.LocalDate fechaActual = java.time.LocalDate.now();
          int edadEnAnios = java.time.Period.between(fechaNacimiento, fechaActual).getYears();

          if (edadEnAnios < 1 && arete_bebe.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Si la vaca tiene menos de 1 año, el arete de bebé es obligatorio.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
          }

        
        com.mycompany.models.Vacas vaca = isEdition ? vacaEdition : new com.mycompany.models.Vacas();
        vaca.setArete(arete);
        vaca.setAlias(alias);
        vaca.setArete_bebe(arete_bebe);
        vaca.setRancho(rancho);
        vaca.setFecha_nacimiento(fechaSql);
        vaca.setRaza(raza);
        vaca.setEmpadre(empadre);
        vaca.setFinalidad(finalidad);
        
        try{
            DAOVacas dao = new DAOVacasImpl();
            if (!isEdition && dao.existeArete(arete)) {
            JOptionPane.showMessageDialog(this, "Ya existe un animal con el arete ingresado.\n", "AVISO", JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            if (!isEdition) dao.registrar(vaca);
            else dao.modificar(vaca);
            
            String message = isEdition ? "modificada" : "registrada";
            javax.swing.JOptionPane.showMessageDialog(this, "Vaca " + message +" correctamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        if (!isEdition){
        aretesTxt.setText("");
        AliasTxt.setText("");
        AreteBebeTxt.setText("");
        RanchoTxt.setText("");
        NacimientoDate.setDate(null);
       
        RazaTxt.setText("");
        EmpadreTxt.setText("");
        FinalidadTxt.setText("");
        aretesTxt.requestFocus();
        }

        }catch(Exception e){
            System.out.println(e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);

            
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void RanchoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RanchoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RanchoTxtActionPerformed

    private void aretesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aretesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aretesTxtActionPerformed

    private void AliasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AliasTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AliasTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel Alias;
    private javax.swing.JTextField AliasTxt;
    private javax.swing.JLabel AreteBebe;
    private javax.swing.JTextField AreteBebeTxt;
    private javax.swing.JLabel Empadre;
    private javax.swing.JTextField EmpadreTxt;
    private javax.swing.JLabel Finalidad;
    private javax.swing.JTextField FinalidadTxt;
    private javax.swing.JLabel Nacimiento;
    private com.toedter.calendar.JDateChooser NacimientoDate;
    private javax.swing.JLabel Rancho;
    private javax.swing.JTextField RanchoTxt;
    private javax.swing.JLabel Raza;
    private javax.swing.JTextField RazaTxt;
    private javax.swing.JLabel TitleG;
    private javax.swing.JLabel aretes;
    private javax.swing.JTextField aretesTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
