/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.agrovacas.DAOVacunasImpl;
import com.mycompany.interfaces.DAOVacunas;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author lalom
 */
public class UpVacunas extends javax.swing.JPanel {

    /**
     * Creates new form MainC
     */
    public UpVacunas() {
        initComponents();
        initStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   private void initStyles(){
       TitleV.putClientProperty( "FlatLaf.styleClass", "h1" );
       TitleV.setForeground(Color.black);
       aretes.putClientProperty( "FlatLaf.styleClass", "h2" );
       aretes.setForeground(Color.black);
       Vacunacion.putClientProperty( "FlatLaf.styleClass", "h2" );
       Vacunacion.setForeground(Color.black);
       Rancho.putClientProperty( "FlatLaf.styleClass", "h2" );
       Rancho.setForeground(Color.black);
       
       //Estilizacion de textfields
       aretesTxt.putClientProperty("JTextField.placeholderText", "Ingrese el Arete");
       VacunaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la Vacuna");
       DosisTxt.putClientProperty("JTextField.placeholderText", "Ingrese la Dosis");
      
   }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        aretes = new javax.swing.JLabel();
        aretesTxt = new javax.swing.JTextField();
        VacunaTxt = new javax.swing.JTextField();
        Rancho = new javax.swing.JLabel();
        Vacunacion = new javax.swing.JLabel();
        VacunacionDate = new com.toedter.calendar.JDateChooser();
        Agregar = new javax.swing.JButton();
        TitleV = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        Dosis = new javax.swing.JLabel();
        DosisTxt = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(858, 471));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        aretes.setText("Arete");

        aretesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aretesTxtActionPerformed(evt);
            }
        });

        VacunaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VacunaTxtActionPerformed(evt);
            }
        });

        Rancho.setText("Vacuna");

        Vacunacion.setText("Fecha de vacunacion");

        Agregar.setBackground(new java.awt.Color(0, 163, 0));
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        TitleV.setText("Agregar Vacunas");
        TitleV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vacunacion.png"))); // NOI18N

        Dosis.setText("Dosis");

        DosisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosisTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(TitleV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(154, 154, 154))
                    .addComponent(VacunacionDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VacunaTxt)
                    .addComponent(aretesTxt)
                    .addComponent(Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aretes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rancho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Vacunacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dosis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DosisTxt))
                .addGap(73, 73, 73)
                .addComponent(Image)
                .addGap(46, 46, 46))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(Image, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addGap(132, 132, 132))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TitleV, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aretes, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aretesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rancho, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VacunaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Dosis, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(DosisTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Vacunacion, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VacunacionDate, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        String arete =aretesTxt.getText();
        String Vacuna =VacunaTxt.getText();
        String dosis = DosisTxt.getText();
        
        
        java.util.Date fechaUtil = VacunacionDate.getDate();
        java.sql.Date fechaSql = null;
        if (fechaUtil != null) {
        fechaSql = new java.sql.Date(fechaUtil.getTime());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fecha de Vacunacion Valida.\n","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return; // Sale del método si no se seleccionó una fecha
        }
        
        if (arete.isEmpty() || Vacuna.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Rellena los campos obligatorios\n","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
             
        try{
            DAOVacunas dao = new DAOVacunasImpl();           
            int animalId = dao.obtenerIdPorArete(arete);
    
        if (animalId == -1) {
        JOptionPane.showMessageDialog(this, "No se encontró ningún animal con ese arete.\n", "AVISO", JOptionPane.WARNING_MESSAGE);
        return;
        }
  
        com.mycompany.models.Vacunas vacuna =  new com.mycompany.models.Vacunas();
        vacuna.setNombre(Vacuna);
        vacuna.setDosis(dosis);
        vacuna.setFechaAplicacion(fechaSql);
        vacuna.setAnimalId(animalId);
        dao.registrar(vacuna);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Vacuna registrada  correctamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
     
        aretesTxt.setText("");
        DosisTxt.setText("");
        VacunaTxt.setText("");
        VacunacionDate.setDate(null);
        aretesTxt.requestFocus();
        

        }catch(Exception e){
            System.out.println(e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);

            
        }
        
    }//GEN-LAST:event_AgregarActionPerformed

    private void VacunaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VacunaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VacunaTxtActionPerformed

    private void aretesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aretesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aretesTxtActionPerformed

    private void DosisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DosisTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel Dosis;
    private javax.swing.JTextField DosisTxt;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Rancho;
    private javax.swing.JLabel TitleV;
    private javax.swing.JTextField VacunaTxt;
    private javax.swing.JLabel Vacunacion;
    private com.toedter.calendar.JDateChooser VacunacionDate;
    private javax.swing.JLabel aretes;
    private javax.swing.JTextField aretesTxt;
    private javax.swing.JPanel bg;
    // End of variables declaration//GEN-END:variables
}
